### ISSUE TITLE
Create template linking Angular and Go server 

### ISSUE THREAD

**Issue by danielwildsmith** [skirill430/Quick-Shop#4]
This is the fundamental component to our website: having a compatible server using Go and client using Angular. 
The tutorial provided is giving us trouble with old packages not working anymore, so simply forking it isn't an option.

**Comment by danielwildsmith** [comment]
Right now, I have the server able to run on port 4200 and print to the console when the URL has a specific "/...". But when the client is running on the same port, nothing is getting printed when I visit the same URL. The client looks the same, but the server functionality disappears...

**Comment by danielwildsmith** [comment]
![Screenshot_20230201_054522](https://user-images.githubusercontent.com/92833122/216182854-5fde1061-9f7a-49f6-bc3d-22728372d652.png)
Some limited functionality.

**Comment by csobolew** [comment]
Just a note, a different port from 4200 should probably be used as it interferes with the angular 'ng serve' debugging port.

**Comment by danielwildsmith** [comment]
So the server and client should have different port numbers?

**Comment by csobolew** [comment]
When we do ng build or something of the sort to make the production version of the front-end that is published, it won't be on port 4200 (HTTP usually uses port 80 and HTTPS uses 443). The backend port doesn't really matter but right now that webgui you showed and the angular test site (ng serve) both have the same ports which, if you have both running, would most likely cause problems.
I also think we could possibly use a subdomain for the backend, but not sure how we would do that. I think the backend showing up only when you do / and then something is intentional because the main website should be running on the main localhost:4200.

**Comment by csobolew** [comment]
Would probably be best to have server on http://localhost/backend/ or something similar and the main site at localhost.

**Comment by danielwildsmith** [comment]
I see the issue. So, they run at the same time on separate ports - how does the backend send some information to the front-end then?

**Comment by csobolew** [comment]
By making a request over HTTP to the backend (localhost:xxxx), just like your browser would do for the web page (localhost:4200). I haven't really read much of this, but it seems like what we're trying to do. A gorilla/mux backend with a PostgreSQL database to go with it: https://semaphoreci.com/community/tutorials/building-and-testing-a-rest-api-in-go-with-gorilla-mux-and-postgresql

**Comment by csobolew** [comment]
Also, if you're just trying to make sure the backend works without worrying about directly connecting it to front end, I think the app Postman is good for that. Otherwise, you would have to write front end TypeScript code to try making requests.

**Comment by danielwildsmith** [comment]
Awesome, thanks so much. For now just to get the basic environment running, I am gonna work on a script that will run both client and server at the same time.
